### PR TITLE
Adding linting and more

### PR DESCRIPTION
**Pull request by vallieres**
Added a few things to your project:

- gitignore and editorconfig
- pre-commit hooks with linting
- fixed all of the linting errors
- added Go Report and GoDock buttons

### CODE REVIEW

**Comment by averagegeek** [comment]
I appreciate the enthusiasm, but the repo is barely 12 hours old and I don't feel that it needs all this stuff just yet (editorconfig, gometalinter config, a general .gitignore, git hooks...). I feel it's imposing a way of working and I don't need this to be honest. It's fine if you work that way, I'm just not.

As for the missing comments on exported members, I already had some WIP on this that'll be pushed soon and I don't think that having a default comment, saying nothing, just to satisfy the linter is better than none. I was about to check for those badges too in the readme, I'll add them when I figured them out which one I need.

**Comment by vallieres** [comment]
I agree the comments mean nothing and that part might need a refactor so it's does not need 30 comments. However, there are many good fixes that were implemented in this PR and found by the linting process. You should still integrate those in your next changes.

As for badges, Go Report looks to be pretty standard and picks up most of what the pre-commit caught. As for the pre-commit, it's fully customizable so you can add or remove linters as you see fit.

Good job by the way! Really like it!

**Comment by averagegeek** [comment]
Thanks for the feedback, I'm still working a bit on it. I had seen the error and defer problem, there is a fix coming to handle defer statements in another way. Again, thanks for the enthusiasm, I didn't meant to be rude by shutting down the PR, just still working on it and didn't felt to include all of this in here at this time.

**Comment by vallieres** [comment]
No troubles :) I'm not that kind of diva! :P

**Pull request closed without merging**
